# basic.yml
#
# This is exactly like basic.yml, except that we're telling deployfish to
# use a different AWS Named Profile to connect to AWS.
#
aws:
  profile: other
  allowed_account_ids:
    - "12134566"

services:
  - name: my-service-elb
    cluster: my-cluster
    count: 2
    load_balancer:
      service_role_arn: arn:aws:iam::123445564666:role/ecsServiceRole
      load_balancer_name: my-elb
      container_name: my-service
      container_port: 80
    family: my-service
    network_mode: bridge
    task_role_arn: arn:aws:iam::123445564666:role/ecsTaskRole
    containers:
      - name: my-service
        image: 123445564666.dkr.ecr.us-west-2.amazonaws.com/my-service:0.1.0
        cpu: 128
        memory: 256
        ports:
          - "80"
        environment:
          - S3_BUCKET=my-bucket
  - name: my-service-alb
    cluster: my-cluster
    count: 2
    load_balancer:
      service_role_arn: arn:aws:iam::123445564666:role/ecsServiceRole
      target_group_arn: arn:aws:elasticloadbalancing:us-west-2:123445564666:targetgroup/my-service-alb/4bf28a0fa5978cea
      container_name: my-service
      container_port: 80
    family: my-service
    network_mode: bridge
    task_role_arn: arn:aws:iam::123445564666:role/ecsTaskRole
    containers:
      - name: my-service
        image: 123445564666.dkr.ecr.us-west-2.amazonaws.com/my-service:0.1.0
        cpu: 128
        memory: 256
        ports:
          - "80"
        environment:
          - S3_BUCKET=my-bucket
