from .adapters import ClickServiceAdapter, ClickServiceSecretsAdapter, ClickServiceTasksAdapter

from .cli import cli

service_group = ClickServiceAdapter.add_command_group(cli, 'service')
service_create = ClickServiceAdapter.add_create_click_command(service_group)
service_update = ClickServiceAdapter.add_update_click_command(service_group)
service_list = ClickServiceAdapter.add_list_click_command(service_group)
service_info = ClickServiceAdapter.add_info_click_command(service_group)
service_exists = ClickServiceAdapter.add_exists_click_command(service_group)
service_delete = ClickServiceAdapter.add_delete_click_command(service_group)
service_ssh = ClickServiceAdapter.add_ssh_click_command(service_group)
service_exec = ClickServiceAdapter.add_exec_click_command(service_group)
service_tunnel = ClickServiceAdapter.add_tunnel_click_command(service_group)
service_scale = ClickServiceAdapter.add_scale_service_click_command(service_group)
service_restart = ClickServiceAdapter.add_restart_service_click_command(service_group)

service_secrets_group = ClickServiceSecretsAdapter.add_command_group(service_group, 'config')
service_secrets_diff = ClickServiceSecretsAdapter.add_diff_secrets_command(service_secrets_group)
service_secrets_show = ClickServiceSecretsAdapter.add_show_secrets_command(service_secrets_group)
service_secrets_write = ClickServiceSecretsAdapter.add_write_secrets_command(service_secrets_group)

service_tasks_group = ClickServiceTasksAdapter.add_command_group(service_group, 'tasks')
service_tasks_list = ClickServiceTasksAdapter.add_list_helper_tasks_click_command(service_tasks_group)
service_tasks_info = ClickServiceTasksAdapter.add_helper_task_info_click_command(service_tasks_group)
service_tasks_run = ClickServiceTasksAdapter.add_run_helper_task_click_command(service_tasks_group)
service_tasks_update = ClickServiceTasksAdapter.add_update_helper_tasks_click_command(service_tasks_group)


@service_tasks_group.group('logs', help='Describe service and task logs')
def service_tasks_logs():
    pass


service_tasks_tail = ClickServiceTasksAdapter.add_tail_logs_click_command(service_tasks_logs)
service_tasks_list = ClickServiceTasksAdapter.add_list_logs_click_command(service_tasks_logs)
